import type { Product } from './types';

const SIZES_APPAREL = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
const SIZES_SHOE = ['6', '7', '8', '9', '10', '11'];
const ONE_SIZE = ['One Size'];

const C = {
  black: { name: 'Black', hex: '#111315' },
  white: { name: 'White', hex: '#F5F6F7' },
  navy: { name: 'Navy', hex: '#16224A' },
  royal: { name: 'Royal Blue', hex: '#1D4ED8' },
  red: { name: 'Sagar Red', hex: '#E31E24' },
  lime: { name: 'Lime', hex: '#C6FF3D' },
  orange: { name: 'Orange', hex: '#FF5A1F' },
  green: { name: 'Bottle Green', hex: '#0F5132' },
  maroon: { name: 'Maroon', hex: '#7A1226' },
  sky: { name: 'Sky Blue', hex: '#38BDF8' },
  grey: { name: 'Grey Melange', hex: '#9AA0A6' },
  yellow: { name: 'Yellow', hex: '#FACC15' },
};

/**
 * PLACEHOLDER CATALOGUE — prices, stock and copy are indicative only.
 * TODO(client): replace with real prices, stock and photography.
 * Every record matches the `Product` type, so this array can be swapped for
 * an API/database response without touching a single component.
 */
export const products: Product[] = [
  /* ------------------------------------------------------------------ */
  /* CUSTOM JERSEYS                                                      */
  /* ------------------------------------------------------------------ */
  {
    id: 'cj-001',
    name: 'Custom Football Jersey',
    slug: 'custom-football-jersey',
    category: 'custom-jerseys',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Full-sublimation football kit built around your club colours, crest and player names. Breathable interlock knit that holds colour through a full season.',
    details:
      'Printed using edge-to-edge dye sublimation so the design becomes part of the fabric — no cracking, no peeling, no added weight. Choose your neck style, pattern and colourway, then add team name, player name, number, club crest and sponsor logos.',
    price: 699,
    salePrice: 599,
    images: [],
    art: { kind: 'jersey', colors: ['#E31E24', '#111315'], pattern: 'chevron' },
    sizes: SIZES_APPAREL,
    colors: [C.lime, C.royal, C.red, C.black, C.navy],
    stock: 500,
    customizable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 126,
    material: '150 GSM polyester interlock, moisture-wicking',
    care: 'Machine wash cold, inside out. Do not bleach. Do not iron on print.',
    specifications: [
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Fabric', value: 'Polyester interlock, 150 GSM' },
      { label: 'Fit', value: 'Athletic regular' },
      { label: 'Neck options', value: 'Round / V / Polo' },
      { label: 'Min. order', value: '1 piece (team pricing from 10)' },
    ],
    tags: ['football', 'jersey', 'custom', 'team', 'sublimation'],
  },
  {
    id: 'cj-002',
    name: 'Custom Cricket Jersey',
    slug: 'custom-cricket-jersey',
    category: 'custom-jerseys',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Match-ready cricket kit with your team identity printed end to end. Collared or round neck, half or full sleeve.',
    details:
      'Designed for long days in the sun — light, quick-drying and colour-locked. Sponsor panels on chest, sleeve and back are included at no extra cost.',
    price: 749,
    images: [],
    art: { kind: 'jersey', colors: ['#1D4ED8', '#FACC15'], pattern: 'sash' },
    sizes: SIZES_APPAREL,
    colors: [C.royal, C.navy, C.maroon, C.green, C.yellow],
    stock: 500,
    customizable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 98,
    material: '160 GSM micro-polyester, quick dry',
    care: 'Machine wash cold, inside out. Line dry in shade.',
    specifications: [
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Fabric', value: 'Micro-polyester, 160 GSM' },
      { label: 'Sleeve', value: 'Half / Full' },
      { label: 'Collar', value: 'Polo / Round' },
      { label: 'Trousers', value: 'Available as a matching set' },
    ],
    tags: ['cricket', 'jersey', 'custom', 'team', 'whites'],
  },
  {
    id: 'cj-003',
    name: 'Custom Basketball Jersey',
    slug: 'custom-basketball-jersey',
    category: 'custom-jerseys',
    sport: 'basketball',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Sleeveless basketball kit with deep-cut armholes and a clean number block. Jersey and shorts sold as a set.',
    price: 899,
    images: [],
    art: { kind: 'jersey', colors: ['#FF5A1F', '#111315'], pattern: 'stripes' },
    sizes: SIZES_APPAREL,
    colors: [C.orange, C.black, C.white, C.royal],
    stock: 220,
    customizable: true,
    featured: true,
    newArrival: true,
    rating: 4.7,
    reviewCount: 41,
    material: 'Polyester mesh, 170 GSM',
    care: 'Machine wash cold. Do not tumble dry.',
    specifications: [
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Cut', value: 'Sleeveless, deep armhole' },
      { label: 'Set', value: 'Jersey + shorts' },
    ],
    tags: ['basketball', 'jersey', 'custom', 'set'],
  },
  {
    id: 'cj-004',
    name: 'Custom Volleyball Jersey',
    slug: 'custom-volleyball-jersey',
    category: 'custom-jerseys',
    sport: 'volleyball',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Lightweight volleyball kit with reinforced shoulder seams and a libero alternate colourway.',
    price: 749,
    images: [],
    art: { kind: 'jersey', colors: ['#38BDF8', '#16224A'], pattern: 'hoops' },
    sizes: SIZES_APPAREL,
    colors: [C.sky, C.navy, C.red, C.lime],
    stock: 180,
    customizable: true,
    featured: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 23,
    specifications: [
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Fabric', value: 'Polyester interlock' },
      { label: 'Extras', value: 'Libero alternate colourway' },
    ],
    tags: ['volleyball', 'jersey', 'custom'],
  },
  {
    id: 'cj-005',
    name: 'Custom Badminton Jersey',
    slug: 'custom-badminton-jersey',
    category: 'custom-jerseys',
    sport: 'badminton',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Feather-light badminton tee with four-way stretch panels under the arm for full overhead range.',
    price: 699,
    images: [],
    art: { kind: 'jersey', colors: ['#E31E24', '#16224A'], pattern: 'solid' },
    sizes: SIZES_APPAREL,
    colors: [C.lime, C.navy, C.white, C.orange],
    stock: 160,
    customizable: true,
    featured: false,
    newArrival: false,
    rating: 4.6,
    reviewCount: 19,
    specifications: [
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Fabric', value: 'Stretch micro-poly, 140 GSM' },
    ],
    tags: ['badminton', 'jersey', 'custom'],
  },
  {
    id: 'cj-006',
    name: 'Custom Teamwear Set',
    slug: 'custom-teamwear-set',
    category: 'custom-jerseys',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Jersey, shorts and matching socks in one package — the full club kit, priced for squads.',
    price: 1199,
    salePrice: 1049,
    images: [],
    art: { kind: 'jersey', colors: ['#DC2626', '#111315'], pattern: 'camo' },
    sizes: SIZES_APPAREL,
    colors: [C.red, C.black, C.royal, C.green],
    stock: 300,
    customizable: true,
    featured: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 64,
    specifications: [
      { label: 'Includes', value: 'Jersey + shorts + socks' },
      { label: 'Print', value: 'Full sublimation' },
      { label: 'Team pricing', value: 'From 10 sets' },
    ],
    tags: ['teamwear', 'kit', 'custom', 'bulk'],
  },

  /* ------------------------------------------------------------------ */
  /* CUSTOM T-SHIRTS                                                     */
  /* ------------------------------------------------------------------ */
  {
    id: 'ct-001',
    name: 'Custom Sports T-Shirt',
    slug: 'custom-sports-t-shirt',
    category: 'custom-tshirts',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Dry-fit training tee with your logo, name or graphic. The workhorse for academies, camps and practice squads.',
    price: 499,
    salePrice: 449,
    images: [],
    art: { kind: 'tshirt', colors: ['#111315', '#E31E24'], pattern: 'solid' },
    sizes: SIZES_APPAREL,
    colors: [C.black, C.white, C.navy, C.grey, C.red],
    stock: 800,
    customizable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.7,
    reviewCount: 211,
    material: '140 GSM polyester dry-fit',
    care: 'Machine wash cold. Do not iron directly on print.',
    specifications: [
      { label: 'Print', value: 'DTF or sublimation' },
      { label: 'Fabric', value: 'Dry-fit polyester' },
      { label: 'Placement', value: 'Front / back / sleeve' },
    ],
    tags: ['t-shirt', 'custom', 'dtf', 'training'],
  },
  {
    id: 'ct-002',
    name: 'Corporate Event T-Shirt',
    slug: 'corporate-event-t-shirt',
    category: 'custom-tshirts',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Cotton-blend event tee for company days, marathons and college fests. DTF printed in full colour.',
    price: 429,
    images: [],
    art: { kind: 'tshirt', colors: ['#F5F6F7', '#1D4ED8'], pattern: 'solid' },
    sizes: SIZES_APPAREL,
    colors: [C.white, C.black, C.royal, C.orange],
    stock: 1000,
    customizable: true,
    featured: false,
    newArrival: false,
    rating: 4.5,
    reviewCount: 87,
    specifications: [
      { label: 'Print', value: 'DTF full colour' },
      { label: 'Fabric', value: 'Cotton-poly blend, 180 GSM' },
      { label: 'Min. order', value: '10 pieces' },
    ],
    tags: ['t-shirt', 'corporate', 'event', 'dtf', 'bulk'],
  },
  {
    id: 'ct-003',
    name: 'Custom Polo T-Shirt',
    slug: 'custom-polo-t-shirt',
    category: 'custom-tshirts',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Collared polo with embroidered or printed branding — staff kits, coaching teams and club merchandise.',
    price: 649,
    images: [],
    art: { kind: 'polo', colors: ['#16224A', '#E31E24'], pattern: 'solid' },
    sizes: SIZES_APPAREL,
    colors: [C.navy, C.black, C.white, C.maroon],
    stock: 400,
    customizable: true,
    featured: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 52,
    specifications: [
      { label: 'Print', value: 'DTF / embroidery' },
      { label: 'Fabric', value: 'Matty polyester' },
      { label: 'Collar', value: 'Tipped rib collar' },
    ],
    tags: ['polo', 'custom', 'corporate', 'embroidery'],
  },

  /* ------------------------------------------------------------------ */
  /* EQUIPMENT — CRICKET                                                 */
  /* ------------------------------------------------------------------ */
  {
    id: 'eq-001',
    name: 'English Willow Cricket Bat',
    slug: 'english-willow-cricket-bat',
    category: 'equipment',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Grade-3 English willow with a mid-to-low sweet spot, straight grains and a thick edge profile.',
    details:
      'Hand-picked clefts, pressed and knocked-in ready for nets. Supplied with a toe guard and anti-scuff sheet.',
    price: 1499,
    salePrice: 1299,
    images: [],
    art: { kind: 'bat', colors: ['#E8D3A9', '#DC2626'] },
    sizes: ['SH', 'H', 'Size 6', 'Size 5'],
    colors: [C.white],
    stock: 34,
    customizable: false,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.6,
    reviewCount: 74,
    specifications: [
      { label: 'Willow', value: 'Grade 3 English willow' },
      { label: 'Weight', value: '1180 – 1250 g' },
      { label: 'Sweet spot', value: 'Mid–low' },
      { label: 'Handle', value: 'Sarawak cane, semi-oval' },
    ],
    tags: ['cricket', 'bat', 'willow', 'equipment'],
  },
  {
    id: 'eq-002',
    name: 'Leather Cricket Ball',
    slug: 'leather-cricket-ball',
    category: 'equipment',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Four-piece alum-tanned leather ball with a hand-stitched seam. Holds shape through a full innings.',
    price: 299,
    images: [],
    art: { kind: 'ball', colors: ['#7A1226', '#F5F6F7'] },
    sizes: ['135 g', '156 g'],
    colors: [C.maroon, C.white],
    stock: 120,
    customizable: false,
    featured: true,
    newArrival: false,
    rating: 4.4,
    reviewCount: 58,
    specifications: [
      { label: 'Construction', value: '4-piece hand stitched' },
      { label: 'Leather', value: 'Alum tanned' },
      { label: 'Weight', value: '156 g (senior)' },
    ],
    tags: ['cricket', 'ball', 'leather', 'equipment'],
  },
  {
    id: 'eq-003',
    name: 'Batting Gloves',
    slug: 'cricket-batting-gloves',
    category: 'protection',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Sausage-finger batting gloves with high-density foam and a breathable mesh back.',
    price: 799,
    images: [],
    art: { kind: 'gloves', colors: ['#F5F6F7', '#1D4ED8'] },
    sizes: ['Youth', 'Mens', 'Mens LH'],
    colors: [C.white, C.royal],
    stock: 60,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.3,
    reviewCount: 31,
    specifications: [
      { label: 'Protection', value: 'HD foam, sausage finger' },
      { label: 'Palm', value: 'Soft cotton leather' },
    ],
    tags: ['cricket', 'gloves', 'protection'],
  },
  {
    id: 'eq-004',
    name: 'Cricket Batting Pads',
    slug: 'cricket-batting-pads',
    category: 'protection',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Lightweight batting pads with cane-reinforced bolsters and quick-release straps.',
    price: 1399,
    images: [],
    art: { kind: 'pads', colors: ['#F5F6F7', '#16224A'] },
    sizes: ['Youth', 'Mens'],
    colors: [C.white],
    stock: 42,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.5,
    reviewCount: 27,
    specifications: [
      { label: 'Bolsters', value: 'Cane reinforced' },
      { label: 'Straps', value: '3 quick-release' },
    ],
    tags: ['cricket', 'pads', 'protection'],
  },
  {
    id: 'eq-005',
    name: 'Cricket Helmet',
    slug: 'cricket-helmet',
    category: 'protection',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'ABS shell helmet with a stainless steel grille and an adjustable rear dial for a locked-in fit.',
    price: 1699,
    images: [],
    art: { kind: 'helmet', colors: ['#16224A', '#9AA0A6'] },
    sizes: ['S', 'M', 'L'],
    colors: [C.navy, C.black, C.maroon],
    stock: 28,
    customizable: false,
    featured: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 18,
    specifications: [
      { label: 'Shell', value: 'High-impact ABS' },
      { label: 'Grille', value: 'Stainless steel' },
      { label: 'Fit', value: 'Rear adjustment dial' },
    ],
    tags: ['cricket', 'helmet', 'protection'],
  },
  {
    id: 'eq-006',
    name: 'Cricket Trousers',
    slug: 'cricket-trousers',
    category: 'sportswear',
    sport: 'cricket',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Classic cricket trousers in easy-care polyester with an elasticated drawcord waist.',
    price: 699,
    images: [],
    art: { kind: 'lower', colors: ['#F5F6F7', '#9AA0A6'] },
    sizes: SIZES_APPAREL,
    colors: [C.white, C.navy],
    stock: 90,
    customizable: true,
    featured: false,
    newArrival: false,
    rating: 4.4,
    reviewCount: 36,
    specifications: [
      { label: 'Fabric', value: 'Poly twill' },
      { label: 'Waist', value: 'Elastic + drawcord' },
    ],
    tags: ['cricket', 'trousers', 'whites', 'sportswear'],
  },

  /* ------------------------------------------------------------------ */
  /* EQUIPMENT — FOOTBALL                                                */
  /* ------------------------------------------------------------------ */
  {
    id: 'eq-010',
    name: 'Match Football',
    slug: 'match-football',
    category: 'equipment',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Thermo-bonded match football with a butyl bladder — true flight, minimal water uptake.',
    price: 599,
    salePrice: 549,
    images: [],
    art: { kind: 'football', colors: ['#F5F6F7', '#111315'] },
    sizes: ['Size 3', 'Size 4', 'Size 5'],
    colors: [C.white, C.lime, C.orange],
    stock: 150,
    customizable: false,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.6,
    reviewCount: 143,
    specifications: [
      { label: 'Construction', value: 'Thermo bonded' },
      { label: 'Bladder', value: 'Butyl, high retention' },
      { label: 'Surface', value: 'Turf / ground' },
    ],
    tags: ['football', 'ball', 'equipment', 'match'],
  },
  {
    id: 'eq-011',
    name: 'Goalkeeper Gloves',
    slug: 'goalkeeper-gloves',
    category: 'protection',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      '4 mm German latex palm with finger-spine protection and a wrap-around wrist strap.',
    price: 899,
    images: [],
    art: { kind: 'gloves', colors: ['#E31E24', '#111315'] },
    sizes: ['7', '8', '9', '10'],
    colors: [C.lime, C.black, C.orange],
    stock: 55,
    customizable: false,
    featured: false,
    newArrival: true,
    rating: 4.5,
    reviewCount: 44,
    specifications: [
      { label: 'Palm', value: '4 mm German latex' },
      { label: 'Protection', value: 'Removable finger spines' },
    ],
    tags: ['football', 'goalkeeper', 'gloves', 'protection'],
  },
  {
    id: 'eq-012',
    name: 'Shin Guards',
    slug: 'shin-guards',
    category: 'protection',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Slim-profile shin guards with EVA backing and an ankle sleeve. Barely there, fully protective.',
    price: 449,
    images: [],
    art: { kind: 'shinguard', colors: ['#111315', '#E31E24'] },
    sizes: ['S', 'M', 'L'],
    colors: [C.black, C.white],
    stock: 110,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.2,
    reviewCount: 39,
    specifications: [
      { label: 'Shell', value: 'PP hard shell' },
      { label: 'Backing', value: 'EVA foam' },
    ],
    tags: ['football', 'shin guards', 'protection'],
  },
  {
    id: 'eq-013',
    name: 'Football Socks',
    slug: 'football-socks',
    category: 'accessories',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Ribbed knee-high football socks with a cushioned footbed and arch compression.',
    price: 249,
    images: [],
    art: { kind: 'socks', colors: ['#1D4ED8', '#F5F6F7'] },
    sizes: ['Free', 'Junior'],
    colors: [C.royal, C.black, C.white, C.red],
    stock: 300,
    customizable: true,
    featured: false,
    newArrival: false,
    rating: 4.3,
    reviewCount: 66,
    specifications: [
      { label: 'Length', value: 'Knee high' },
      { label: 'Footbed', value: 'Terry cushioned' },
    ],
    tags: ['football', 'socks', 'accessories'],
  },
  {
    id: 'eq-014',
    name: 'Training Cone Set',
    slug: 'training-cone-set',
    category: 'equipment',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Set of 20 flexible marker cones with a carry stand — drills, grids and agility work.',
    price: 549,
    images: [],
    art: { kind: 'net', colors: ['#FF5A1F', '#111315'] },
    sizes: ONE_SIZE,
    colors: [C.orange, C.yellow],
    stock: 70,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.4,
    reviewCount: 22,
    specifications: [
      { label: 'Quantity', value: '20 cones + stand' },
      { label: 'Material', value: 'Flexible PVC' },
    ],
    tags: ['training', 'cones', 'equipment', 'agility'],
  },

  /* ------------------------------------------------------------------ */
  /* EQUIPMENT — BASKETBALL / BADMINTON                                  */
  /* ------------------------------------------------------------------ */
  {
    id: 'eq-020',
    name: 'Basketball',
    slug: 'basketball',
    category: 'equipment',
    sport: 'basketball',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Deep-channel composite basketball with a tacky pebbled grip. Indoor and outdoor rated.',
    price: 699,
    images: [],
    art: { kind: 'basketball', colors: ['#FF5A1F', '#111315'] },
    sizes: ['Size 5', 'Size 6', 'Size 7'],
    colors: [C.orange],
    stock: 80,
    customizable: false,
    featured: true,
    newArrival: false,
    rating: 4.5,
    reviewCount: 61,
    specifications: [
      { label: 'Cover', value: 'Composite leather' },
      { label: 'Use', value: 'Indoor / outdoor' },
      { label: 'Size', value: '7 (official)' },
    ],
    tags: ['basketball', 'ball', 'equipment'],
  },
  {
    id: 'eq-021',
    name: 'Badminton Racket',
    slug: 'badminton-racket',
    category: 'equipment',
    sport: 'badminton',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Full-graphite racket, 85 g, even balance — control for rallies, snap for smashes.',
    price: 999,
    salePrice: 899,
    images: [],
    art: { kind: 'racket', colors: ['#E31E24', '#111315'] },
    sizes: ['G4', 'G5'],
    colors: [C.lime, C.red, C.navy],
    stock: 65,
    customizable: false,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.6,
    reviewCount: 95,
    specifications: [
      { label: 'Frame', value: 'Full graphite' },
      { label: 'Weight', value: '85 g (3U)' },
      { label: 'Balance', value: 'Even' },
      { label: 'Tension', value: 'Up to 28 lbs' },
    ],
    tags: ['badminton', 'racket', 'graphite', 'equipment'],
  },
  {
    id: 'eq-022',
    name: 'Feather Shuttlecock (Box of 6)',
    slug: 'feather-shuttlecock',
    category: 'equipment',
    sport: 'badminton',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Grade-A duck feather shuttles with a natural cork base. Stable flight, tournament speed 77.',
    price: 399,
    images: [],
    art: { kind: 'shuttle', colors: ['#F5F6F7', '#E31E24'] },
    sizes: ['Speed 76', 'Speed 77', 'Speed 78'],
    colors: [C.white],
    stock: 200,
    customizable: false,
    featured: true,
    newArrival: false,
    rating: 4.4,
    reviewCount: 72,
    specifications: [
      { label: 'Feather', value: 'Grade A duck' },
      { label: 'Base', value: 'Natural cork' },
      { label: 'Pack', value: '6 shuttles' },
    ],
    tags: ['badminton', 'shuttlecock', 'feather'],
  },
  {
    id: 'eq-023',
    name: 'Badminton Net',
    slug: 'badminton-net',
    category: 'equipment',
    sport: 'badminton',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Full-size nylon net with a reinforced tape top and side ropes. Court-ready in minutes.',
    price: 899,
    images: [],
    art: { kind: 'net', colors: ['#111315', '#E31E24'] },
    sizes: ONE_SIZE,
    colors: [C.black],
    stock: 40,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.2,
    reviewCount: 17,
    specifications: [
      { label: 'Size', value: '6.1 m × 0.76 m' },
      { label: 'Material', value: 'Braided nylon' },
    ],
    tags: ['badminton', 'net', 'equipment'],
  },
  {
    id: 'eq-024',
    name: 'Racket Grip (Pack of 3)',
    slug: 'racket-grip-pack',
    category: 'accessories',
    sport: 'badminton',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Tacky PU overgrips that stay dry through long sets. Three per pack.',
    price: 199,
    images: [],
    art: { kind: 'racket', colors: ['#38BDF8', '#111315'] },
    sizes: ONE_SIZE,
    colors: [C.sky, C.black, C.lime],
    stock: 250,
    customizable: false,
    featured: false,
    newArrival: true,
    rating: 4.3,
    reviewCount: 48,
    specifications: [
      { label: 'Material', value: 'PU tacky' },
      { label: 'Pack', value: '3 grips' },
    ],
    tags: ['badminton', 'grip', 'accessories'],
  },

  /* ------------------------------------------------------------------ */
  /* FOOTWEAR                                                            */
  /* ------------------------------------------------------------------ */
  {
    id: 'fw-001',
    name: 'Running Shoes',
    slug: 'running-shoes',
    category: 'footwear',
    sport: 'running',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Cushioned daily trainer with a breathable engineered mesh upper and a high-rebound EVA midsole.',
    price: 1999,
    salePrice: 1699,
    images: [],
    art: { kind: 'shoe', colors: ['#111315', '#E31E24'] },
    sizes: SIZES_SHOE,
    colors: [C.black, C.white, C.lime],
    stock: 75,
    customizable: false,
    featured: true,
    newArrival: true,
    bestSeller: true,
    rating: 4.5,
    reviewCount: 132,
    specifications: [
      { label: 'Upper', value: 'Engineered mesh' },
      { label: 'Midsole', value: 'High-rebound EVA' },
      { label: 'Drop', value: '8 mm' },
      { label: 'Use', value: 'Road / daily training' },
    ],
    tags: ['running', 'shoes', 'footwear'],
  },
  {
    id: 'fw-002',
    name: 'Sports Shoes',
    slug: 'sports-shoes',
    category: 'footwear',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'All-court training shoe with a grippy non-marking outsole and a padded collar.',
    price: 1799,
    images: [],
    art: { kind: 'shoe', colors: ['#F5F6F7', '#1D4ED8'] },
    sizes: SIZES_SHOE,
    colors: [C.white, C.royal, C.black],
    stock: 90,
    customizable: false,
    featured: true,
    newArrival: false,
    rating: 4.3,
    reviewCount: 88,
    specifications: [
      { label: 'Outsole', value: 'Non-marking rubber' },
      { label: 'Use', value: 'Court / gym / multi-sport' },
    ],
    tags: ['sports', 'shoes', 'footwear', 'training'],
  },
  {
    id: 'fw-003',
    name: 'Football Studs',
    slug: 'football-studs',
    category: 'footwear',
    sport: 'football',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Firm-ground boots with a textured strike zone and conical studs for quick turns.',
    price: 2299,
    images: [],
    art: { kind: 'shoe', colors: ['#FF5A1F', '#111315'] },
    sizes: SIZES_SHOE,
    colors: [C.orange, C.black, C.lime],
    stock: 48,
    customizable: false,
    featured: false,
    newArrival: true,
    rating: 4.4,
    reviewCount: 37,
    specifications: [
      { label: 'Surface', value: 'Firm ground' },
      { label: 'Studs', value: 'Conical TPU' },
    ],
    tags: ['football', 'boots', 'studs', 'footwear'],
  },

  /* ------------------------------------------------------------------ */
  /* SPORTSWEAR                                                          */
  /* ------------------------------------------------------------------ */
  {
    id: 'sw-001',
    name: 'Sports Lower',
    slug: 'sports-lower',
    category: 'sportswear',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Tapered training lower with zip pockets and an ankle cuff that stays put through drills.',
    price: 699,
    salePrice: 629,
    images: [],
    art: { kind: 'lower', colors: ['#111315', '#E31E24'] },
    sizes: SIZES_APPAREL,
    colors: [C.black, C.navy, C.grey],
    stock: 180,
    customizable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    rating: 4.5,
    reviewCount: 156,
    material: 'NS lycra, four-way stretch',
    care: 'Machine wash cold. Tumble dry low.',
    specifications: [
      { label: 'Fit', value: 'Tapered' },
      { label: 'Pockets', value: '2 zip side pockets' },
      { label: 'Cuff', value: 'Ribbed ankle' },
    ],
    tags: ['lower', 'track pants', 'sportswear', 'training'],
  },
  {
    id: 'sw-002',
    name: 'Tracksuit Set',
    slug: 'tracksuit-set',
    category: 'sportswear',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Jacket and lower set with contrast piping. Customisable with your club name and crest.',
    price: 1499,
    salePrice: 1349,
    images: [],
    art: { kind: 'tracksuit', colors: ['#16224A', '#FF5A1F'] },
    sizes: SIZES_APPAREL,
    colors: [C.navy, C.black, C.maroon, C.royal],
    stock: 120,
    customizable: true,
    featured: true,
    newArrival: true,
    rating: 4.7,
    reviewCount: 79,
    material: 'Poly-cotton, fleece back',
    care: 'Machine wash cold, inside out.',
    specifications: [
      { label: 'Includes', value: 'Jacket + lower' },
      { label: 'Closure', value: 'Full-length zip' },
      { label: 'Branding', value: 'Print or embroidery' },
    ],
    tags: ['tracksuit', 'sportswear', 'custom', 'team'],
  },
  {
    id: 'sw-003',
    name: 'Training Shorts',
    slug: 'training-shorts',
    category: 'sportswear',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Lightweight shorts with an inner brief and side splits for a full stride.',
    price: 449,
    images: [],
    art: { kind: 'shorts', colors: ['#111315', '#F5F6F7'] },
    sizes: SIZES_APPAREL,
    colors: [C.black, C.navy, C.royal, C.red],
    stock: 220,
    customizable: true,
    featured: false,
    newArrival: false,
    rating: 4.4,
    reviewCount: 64,
    specifications: [
      { label: 'Fabric', value: 'Polyester dry-fit' },
      { label: 'Inner', value: 'Brief lining' },
    ],
    tags: ['shorts', 'sportswear', 'training'],
  },
  {
    id: 'sw-004',
    name: 'Sports Cap',
    slug: 'sports-cap',
    category: 'accessories',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Six-panel cap with a curved brim and a sweat-wicking band. Add your crest in embroidery.',
    price: 399,
    images: [],
    art: { kind: 'cap', colors: ['#111315', '#E31E24'] },
    sizes: ONE_SIZE,
    colors: [C.black, C.navy, C.white, C.red],
    stock: 260,
    customizable: true,
    featured: true,
    newArrival: false,
    rating: 4.2,
    reviewCount: 53,
    specifications: [
      { label: 'Panels', value: '6 panel, curved brim' },
      { label: 'Closure', value: 'Adjustable strap' },
      { label: 'Branding', value: 'Embroidery / DTF' },
    ],
    tags: ['cap', 'accessories', 'custom'],
  },
  {
    id: 'sw-005',
    name: 'Sports Socks (Pack of 3)',
    slug: 'sports-socks-pack',
    category: 'accessories',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Ankle-length cushioned socks with arch support. Three pairs per pack.',
    price: 299,
    images: [],
    art: { kind: 'socks', colors: ['#F5F6F7', '#111315'] },
    sizes: ['Free'],
    colors: [C.white, C.black, C.grey],
    stock: 400,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.3,
    reviewCount: 41,
    specifications: [
      { label: 'Pack', value: '3 pairs' },
      { label: 'Length', value: 'Ankle' },
    ],
    tags: ['socks', 'accessories'],
  },
  {
    id: 'sw-006',
    name: 'Sports T-Shirt',
    slug: 'sports-t-shirt',
    category: 'sportswear',
    sport: 'training',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Everyday dry-fit tee with raglan sleeves and a clean chest mark.',
    price: 449,
    images: [],
    art: { kind: 'tshirt', colors: ['#16224A', '#E31E24'], pattern: 'solid' },
    sizes: SIZES_APPAREL,
    colors: [C.navy, C.black, C.grey, C.lime],
    stock: 340,
    customizable: true,
    featured: false,
    newArrival: true,
    rating: 4.4,
    reviewCount: 92,
    specifications: [
      { label: 'Fabric', value: 'Dry-fit polyester' },
      { label: 'Sleeve', value: 'Raglan' },
    ],
    tags: ['t-shirt', 'sportswear', 'training'],
  },

  /* ------------------------------------------------------------------ */
  /* PROTECTION / SUPPORTS                                               */
  /* ------------------------------------------------------------------ */
  {
    id: 'pr-001',
    name: 'Knee Support',
    slug: 'knee-support',
    category: 'protection',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Compression knee sleeve with a silicone patella ring and anti-slip bands.',
    price: 499,
    images: [],
    art: { kind: 'support', colors: ['#111315', '#FF5A1F'] },
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [C.black],
    stock: 140,
    customizable: false,
    featured: true,
    newArrival: false,
    rating: 4.4,
    reviewCount: 68,
    specifications: [
      { label: 'Support', value: 'Silicone patella ring' },
      { label: 'Fabric', value: 'Nylon-spandex knit' },
    ],
    tags: ['knee', 'support', 'protection'],
  },
  {
    id: 'pr-002',
    name: 'Elbow Support',
    slug: 'elbow-support',
    category: 'protection',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Graduated compression elbow sleeve for racket and throwing sports.',
    price: 399,
    images: [],
    art: { kind: 'support', colors: ['#16224A', '#38BDF8'] },
    sizes: ['S', 'M', 'L'],
    colors: [C.black, C.navy],
    stock: 130,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.2,
    reviewCount: 29,
    specifications: [{ label: 'Fabric', value: 'Nylon-spandex knit' }],
    tags: ['elbow', 'support', 'protection'],
  },
  {
    id: 'pr-003',
    name: 'Wrist Support',
    slug: 'wrist-support',
    category: 'protection',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Adjustable wrist wrap with a thumb loop — gym, cricket and racket sports.',
    price: 299,
    images: [],
    art: { kind: 'support', colors: ['#111315', '#E31E24'] },
    sizes: ONE_SIZE,
    colors: [C.black, C.grey],
    stock: 190,
    customizable: false,
    featured: false,
    newArrival: false,
    rating: 4.1,
    reviewCount: 34,
    specifications: [{ label: 'Closure', value: 'Hook and loop' }],
    tags: ['wrist', 'support', 'protection'],
  },
  {
    id: 'pr-004',
    name: 'Ankle Support',
    slug: 'ankle-support',
    category: 'protection',
    sport: 'multi',
    brand: 'Sagar Sportz',
    gender: 'unisex',
    description:
      'Compression ankle sleeve with figure-8 strapping for lateral stability.',
    price: 399,
    images: [],
    art: { kind: 'support', colors: ['#7A1226', '#F5F6F7'] },
    sizes: ['S', 'M', 'L'],
    colors: [C.black, C.maroon],
    stock: 120,
    customizable: false,
    featured: false,
    newArrival: true,
    rating: 4.3,
    reviewCount: 26,
    specifications: [{ label: 'Support', value: 'Figure-8 strap' }],
    tags: ['ankle', 'support', 'protection'],
  },
];

/* -------------------------------------------------------------------- */
/* Selectors — keep filtering logic out of components.                   */
/* -------------------------------------------------------------------- */

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getFeatured = (limit?: number) => {
  const list = products.filter((p) => p.featured);
  return limit ? list.slice(0, limit) : list;
};

export const getNewArrivals = (limit?: number) => {
  const list = products.filter((p) => p.newArrival);
  return limit ? list.slice(0, limit) : list;
};

export const getByCategory = (category: string, limit?: number) => {
  const list = products.filter((p) => p.category === category);
  return limit ? list.slice(0, limit) : list;
};

export const getBySport = (sport: string, limit?: number) => {
  const list = products.filter((p) => p.sport === sport);
  return limit ? list.slice(0, limit) : list;
};

export const getCustomisable = (limit?: number) => {
  const list = products.filter((p) => p.customizable);
  return limit ? list.slice(0, limit) : list;
};

export const getRelated = (product: Product, limit = 4) =>
  products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.sport === product.sport || p.category === product.category),
    )
    .slice(0, limit);

export const effectivePrice = (p: Product) => p.salePrice ?? p.price;

export const discountPercent = (p: Product) =>
  p.salePrice ? Math.round(((p.price - p.salePrice) / p.price) * 100) : 0;

export const allBrands = Array.from(new Set(products.map((p) => p.brand)));
export const allSizes = Array.from(new Set(products.flatMap((p) => p.sizes)));
